<h2> Part I: Uploading & Cleaning Dataset 1- DOHMH New York City Restaurant Inspection Results </h2>

In [1]:
import pandas as pd
import numpy as np

# Uploading the DOHMH New York City Restaurant Inspection Results
df = pd.read_csv("DOHMH_NYC_Restaurant_Inspection_Results_20241110.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'DOHMH_NYC_Restaurant_Inspection_Results_20241110.csv'

In [2]:
# Removing columns that are not relevant to the project
df = df.drop(columns=["BUILDING","STREET","VIOLATION CODE","CRITICAL FLAG","RECORD DATE","INSPECTION TYPE","Community Board", 
                     "Council District","Census Tract","BIN","BBL","NTA","Location Point1"]) 
df
# Double check if we want to keep CAMIS, Phone, Action, and I think that INSPECTION DATE and GRADE DATE have the same data so we can keep GRADE DATE

NameError: name 'df' is not defined

In [7]:
# Checking for NaN values
print(df.isna().any()) # Must eliminate NaN values

CAMIS                    False
DBA                       True
BORO                     False
ZIPCODE                   True
PHONE                     True
CUISINE DESCRIPTION       True
INSPECTION DATE          False
ACTION                    True
VIOLATION DESCRIPTION     True
SCORE                     True
GRADE                     True
GRADE DATE                True
Latitude                  True
Longitude                 True
dtype: bool

In [8]:
# Dropping NaN Values
df.dropna(inplace=True)
df

,CAMIS,DBA,BORO,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION DESCRIPTION,SCORE,GRADE,GRADE DATE,Latitude,Longitude
43,50104071,SHAHI DARBAR,Queens,11372.0,2124775373,Bangladeshi,02/20/2024,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,12.0,A,02/20/2024,40.747498,-73.893356
49,50086256,TAKESHI SUSHI,Manhattan,10013.0,9176750771,Japanese,02/01/2024,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,12.0,A,02/01/2024,40.722834,-74.004719
52,40783903,ALICE,Manhattan,10011.0,2126914886,Italian,12/27/2022,Violations were cited in the following area(s).,Live roaches in facility's food or non-food area.,9.0,A,12/27/2022,40.737058,-73.998300
53,50117299,ARIA KABAB,Queens,11103.0,9172947529,Afghan,03/11/2024,Violations were cited in the following area(s).,Thawing procedure improper.,11.0,A,03/11/2024,40.767540,-73.912032
77,50103156,IKUMI,Manhattan,10012.0,9178822734,Japanese,08/05/2021,Violations were cited in the following area(s).,Hand wash sign not posted,10.0,A,08/05/2021,40.726745,-74.002121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258210,50053441,PANDA EXPRESS #2622,Manhattan,10036.0,2129699289,Chinese,03/03/2022,Violations were cited in the following area(s).,Covered garbage receptacle not provided or ina...,12.0,A,03/03/2022,40.760893,-73.990838
258211,50133642,MATCHA Cafe MAIKO,Queens,11354.0,3473998961,Coffee/Tea,04/17/2024,Violations were cited in the following area(s).,Anti-siphonage or back-flow prevention device ...,4.0,A,04/17/2024,40.759110,-73.834161
258213,50115226,DOUBLE CHINESE RESTAURANT,Queens,11368.0,7187601021,Chinese,10/05/2022,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,11.0,A,10/05/2022,40.742518,-73.854548
258214,40843676,PAZZA NOTTE,Manhattan,10019.0,2127656288,Italian,09/20/2022,Violations were cited in the following area(s).,Non-food contact surface or equipment made of ...,11.0,A,09/20/2022,40.763463,-73.977828
258216,50044403,HONG KONG DIM SUN,Brooklyn,11220.0,7184390836,Chinese,05/15/2024,Violations were cited in the following area(s).,"Food, supplies, or equipment not protected fro...",13.0,A,05/15/2024,40.635901,-74.010229

<h2> Questions</h2>
<li> How much should we sample from the dataset? It's too large to use entirely</li>
<li> Should we filter by GRADE DATE/INSPECTION DATE (whichever one we keep), as in establish a date range for our data?</li>
<li> We have a lot of categorical columns. Will we need to do one-hot encoding for some of them (especially the grades)?</li>

<h2>Part II: Getting Information from Dataset 1</h2>

In [9]:
# Creating a violation_df that contains rows with actual violations
violation_df = df[df["ACTION"].isin([
    "Violations were cited in the following area(s).",
    "Establishment Closed by DOHMH. Violations were cited in the following area(s) and those requiring immediate action were addressed."
])]
violation_df = violation_df.drop(columns=["ACTION"]) # Dropping ACTION because it's already established that all of these restaurants had violations
violation_df

,CAMIS,DBA,BORO,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,VIOLATION DESCRIPTION,SCORE,GRADE,GRADE DATE,Latitude,Longitude
43,50104071,SHAHI DARBAR,Queens,11372.0,2124775373,Bangladeshi,02/20/2024,Hot TCS food item not held at or above 140 °F.,12.0,A,02/20/2024,40.747498,-73.893356
49,50086256,TAKESHI SUSHI,Manhattan,10013.0,9176750771,Japanese,02/01/2024,Hot TCS food item not held at or above 140 °F.,12.0,A,02/01/2024,40.722834,-74.004719
52,40783903,ALICE,Manhattan,10011.0,2126914886,Italian,12/27/2022,Live roaches in facility's food or non-food area.,9.0,A,12/27/2022,40.737058,-73.998300
53,50117299,ARIA KABAB,Queens,11103.0,9172947529,Afghan,03/11/2024,Thawing procedure improper.,11.0,A,03/11/2024,40.767540,-73.912032
77,50103156,IKUMI,Manhattan,10012.0,9178822734,Japanese,08/05/2021,Hand wash sign not posted,10.0,A,08/05/2021,40.726745,-74.002121
...,...,...,...,...,...,...,...,...,...,...,...,...,...
258210,50053441,PANDA EXPRESS #2622,Manhattan,10036.0,2129699289,Chinese,03/03/2022,Covered garbage receptacle not provided or ina...,12.0,A,03/03/2022,40.760893,-73.990838
258211,50133642,MATCHA Cafe MAIKO,Queens,11354.0,3473998961,Coffee/Tea,04/17/2024,Anti-siphonage or back-flow prevention device ...,4.0,A,04/17/2024,40.759110,-73.834161
258213,50115226,DOUBLE CHINESE RESTAURANT,Queens,11368.0,7187601021,Chinese,10/05/2022,Hot TCS food item not held at or above 140 °F.,11.0,A,10/05/2022,40.742518,-73.854548
258214,40843676,PAZZA NOTTE,Manhattan,10019.0,2127656288,Italian,09/20/2022,Non-food contact surface or equipment made of ...,11.0,A,09/20/2022,40.763463,-73.977828
258216,50044403,HONG KONG DIM SUN,Brooklyn,11220.0,7184390836,Chinese,05/15/2024,"Food, supplies, or equipment not protected fro...",13.0,A,05/15/2024,40.635901,-74.010229

In [10]:
# Finding violation counts per borough
violation_counts_per_borough = violation_df["BORO"].value_counts()

print("Violation counts per borough:")
print(violation_counts_per_borough)

Violation counts per borough:
BORO
Manhattan        41058
Brooklyn         29752
Queens           25912
Bronx             9860
Staten Island     4404
Name: count, dtype: int64

In [11]:
# Find the borough with the most violations and its count
borough_with_most_violations = violation_counts_per_borough.idxmax()
borough_with_most_violations_count = violation_counts_per_borough.max()

print(borough_with_most_violations, "is the borough with the most violations, with a total of", borough_with_most_violations_count, "violations.")

Manhattan is the borough with the most violations, with a total of 41058 violations.

In [12]:
# Finding the most common violation in all of NYC and its count
most_common_violation = violation_df["VIOLATION DESCRIPTION"].value_counts().idxmax()
most_common_violation_count = violation_df["VIOLATION DESCRIPTION"].value_counts().max()

print("The most common violation in all of NYC is:", most_common_violation)
print("This violation occured", most_common_violation_count, "times.")

The most common violation in all of NYC is: Non-food contact surface or equipment made of unacceptable material, not kept clean, or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.
This violation occured 17226 times.

In [13]:
# Finding the most common violation per borough and its count
most_common_violation_per_borough = (violation_df.groupby("BORO")["VIOLATION DESCRIPTION"].apply(lambda x: x.value_counts().head(1))).reset_index()
most_common_violation_per_borough.columns = ["BORO", "VIOLATION DESCRIPTION", "COUNT"]

print("The most common violation per borough and its count:")
print(most_common_violation_per_borough)

The most common violation per borough and its count:
            BORO                              VIOLATION DESCRIPTION  COUNT
0          Bronx  Non-food contact surface or equipment made of ...   1768
1       Brooklyn  Non-food contact surface or equipment made of ...   4516
2      Manhattan  Non-food contact surface or equipment made of ...   6420
3         Queens  Non-food contact surface or equipment made of ...   3683
4  Staten Island  Non-food contact surface or equipment made of ...    839

In [14]:
# Finding the borough and cuisine combination with the most violations
cuisine_borough_combo = violation_df.groupby(["BORO", "CUISINE DESCRIPTION"]).size().idxmax()
combo_violation_count = violation_df.groupby(['BORO', "CUISINE DESCRIPTION"]).size().max()

print("The borough and cuisine combination with the most violations is", cuisine_borough_combo[0],"and",cuisine_borough_combo[1],"cuisine.")
print("The number of violations for this combination is", combo_violation_count)

The borough and cuisine combination with the most violations is Manhattan and American cuisine.
The number of violations for this combination is 9569

In [15]:
# Finding the most common cuisine per borough and its count (not using violation_df)
most_common_cuisine_per_borough = (df.groupby("BORO")["CUISINE DESCRIPTION"].apply(lambda x: x.value_counts().head(1))).reset_index()
most_common_cuisine_per_borough.columns = ["BORO", "CUISINE DESCRIPTION", "COUNT"]

print("The most common cuisine per borough and its count:")
print(most_common_cuisine_per_borough)

The most common cuisine per borough and its count:
            BORO CUISINE DESCRIPTION  COUNT
0          Bronx            American   1164
1       Brooklyn            American   4505
2      Manhattan            American   9626
3         Queens            American   3614
4  Staten Island            American    896

In [36]:
dfgoogle = pd.read_csv("google_maps_restaurants(cleaned).csv")
dfgoogle.rename(columns={"Name" :"DBA", "Lat": "Latitude", "Lon": "Longitude", "ZipCode": "ZIPCODE"}, inplace= True)
dfgoogle["DBA"]= dfgoogle["DBA"].str.upper()
#dfgoogle

dfgoogle["ZIPCODE"] = dfgoogle["ZIPCODE"].astype(int)
dfgoogle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670 entries, 0 to 669
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   URL               670 non-null    object
 1   DBA               670 non-null    object
 2   Rating            666 non-null    float64
 3   Rating Count      666 non-null    float64
 4   Detailed Ratings  670 non-null    object
 5   Price Category    547 non-null    float64
 6   Address           670 non-null    object
 7   Latitude          670 non-null    float64
 8   Longitude         670 non-null    float64
 9   ZIPCODE           670 non-null    int64
dtypes: float64(5), int64(1), object(4)
memory usage: 52.5+ KB

In [25]:
merged = pd.merge(df,dfgoogle, on = "DBA", how = "inner" )
merged.dropna()
merged

,CAMIS,DBA,BORO,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION DESCRIPTION,SCORE,...,Longitude,URL,Rating,Rating Count,Detailed Ratings,Price Category,Address,Lat,Lon,ZipCode
0,50102573,A GUSTO,Brooklyn,11216.0,3475339961,Thai,01/26/2024,Violations were cited in the following area(s).,Thawing procedure improper.,7.0,...,-73.942624,https://www.google.com/maps/place/A+Gusto/data...,3.9,233.0,"{'Rating 5 ': 136.0, 'Rating 4 ': 31.0, 'Ratin...",2.0,"1450 Fulton St, Brooklyn, NY 11216",40.679860,-73.942853,11216
1,50102646,TACOMBI,Manhattan,10004.0,9172617136,Tex-Mex,05/14/2024,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,12.0,...,-74.011570,https://www.google.com/maps/place/Tacombi/data...,4.4,802.0,"{'Rating 5 ': 514.0, 'Rating 4 ': 165.0, 'Rati...",2.0,"74 Broad St, New York, NY 10004",40.704688,-74.011667,10004
2,50117190,DIG,Manhattan,10017.0,2123352010,American,04/27/2022,Violations were cited in the following area(s).,Hot food item not held at or above 140º F.,13.0,...,-73.980084,https://www.google.com/maps/place/DIG/data=!4m...,4.3,547.0,"{'Rating 5 ': 295.0, 'Rating 4 ': 164.0, 'Rati...",1.0,"80 Pine St, New York, NY 10005",40.706091,-74.007293,10005
3,50117190,DIG,Manhattan,10017.0,2123352010,American,04/27/2022,Violations were cited in the following area(s).,Hot food item not held at or above 140º F.,13.0,...,-73.980084,https://www.google.com/maps/place/DIG/data=!4m...,4.1,168.0,"{'Rating 5 ': 91.0, 'Rating 4 ': 41.0, 'Rating...",1.0,"225 Liberty St, New York, NY 10281",40.712748,-74.015579,10281
4,50117190,DIG,Manhattan,10017.0,2123352010,American,04/27/2022,Violations were cited in the following area(s).,Hot food item not held at or above 140º F.,13.0,...,-73.980084,https://www.google.com/maps/place/DIG/data=!4m...,4.1,50.0,"{'Rating 5 ': 37.0, 'Rating 4 ': 0.0, 'Rating ...",2.0,"138 Willoughby St, Brooklyn, NY 11201",40.691980,-73.983168,11201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4958,41656235,SUBWAY,Staten Island,10303.0,7187275222,Sandwiches,06/28/2024,Violations were cited in the following area(s).,Non-food contact surface or equipment made of ...,13.0,...,-74.164119,https://www.google.com/maps/place/Subway/data=...,3.8,321.0,"{'Rating 5 ': 131.0, 'Rating 4 ': 84.0, 'Ratin...",1.0,"11 Broadway Unit #155, New York, NY 10004",40.705120,-74.014046,10004
4959,41656235,SUBWAY,Staten Island,10303.0,7187275222,Sandwiches,06/28/2024,Violations were cited in the following area(s).,Non-food contact surface or equipment made of ...,13.0,...,-74.164119,https://www.google.com/maps/place/Subway/data=...,3.8,607.0,"{'Rating 5 ': 279.0, 'Rating 4 ': 118.0, 'Rati...",1.0,"2866 John F. Kennedy Blvd, Jersey City, NJ 07306",40.731416,-74.064682,7306
4960,41561572,SUBWAY,Queens,11374.0,7182712001,Sandwiches,09/13/2022,Violations were cited in the following area(s).,Toilet facility not maintained or provided wit...,7.0,...,-73.864192,https://www.google.com/maps/place/Subway/data=...,3.5,92.0,"{'Rating 5 ': 39.0, 'Rating 4 ': 17.0, 'Rating...",1.0,"1724 Victory Blvd, Staten Island, NY 10314",40.612885,-74.121188,10314
4961,41561572,SUBWAY,Queens,11374.0,7182712001,Sandwiches,09/13/2022,Violations were cited in the following area(s).,Toilet facility not maintained or provided wit...,7.0,...,-73.864192,https://www.google.com/maps/place/Subway/data=...,3.8,321.0,"{'Rating 5 ': 131.0, 'Rating 4 ': 84.0, 'Ratin...",1.0,"11 Broadway Unit #155, New York, NY 10004",40.705120,-74.014046,10004
4962,41561572,SUBWAY,Queens,11374.0,7182712001,Sandwiches,09/13/2022,Violations were cited in the following area(s).,Toilet facility not maintained or provided wit...,7.0,...,-73.864192,https://www.google.com/maps/place/Subway/data=...,3.8,607.0,"{'Rating 5 ': 279.0, 'Rating 4 ': 118.0, 'Rati...",1.0,"2866 John F. Kennedy Blvd, Jersey City, NJ 07306",40.731416,-74.064682,7306

In [37]:
merged = pd.merge(df,dfgoogle, on = ["DBA", "ZIPCODE"], how = "inner" )
merged.dropna()
merged

,CAMIS,DBA,BORO,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION DESCRIPTION,SCORE,...,Latitude_x,Longitude_x,URL,Rating,Rating Count,Detailed Ratings,Price Category,Address,Latitude_y,Longitude_y
0,50102573,A GUSTO,Brooklyn,11216,3475339961,Thai,01/26/2024,Violations were cited in the following area(s).,Thawing procedure improper.,7.0,...,40.680001,-73.942624,https://www.google.com/maps/place/A+Gusto/data...,3.9,233.0,"{'Rating 5 ': 136.0, 'Rating 4 ': 31.0, 'Ratin...",2.0,"1450 Fulton St, Brooklyn, NY 11216",40.679860,-73.942853
1,50102646,TACOMBI,Manhattan,10004,9172617136,Tex-Mex,05/14/2024,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,12.0,...,40.704644,-74.011570,https://www.google.com/maps/place/Tacombi/data...,4.4,802.0,"{'Rating 5 ': 514.0, 'Rating 4 ': 165.0, 'Rati...",2.0,"74 Broad St, New York, NY 10004",40.704688,-74.011667
2,41472400,MAIZAL RESTAURANT,Staten Island,10305,3478253776,Mexican,08/04/2022,Violations were cited in the following area(s).,Hot TCS food item not held at or above 140 °F.,7.0,...,40.618429,-74.069343,https://www.google.com/maps/place/Maizal+Resta...,4.4,403.0,"{'Rating 5 ': 262.0, 'Rating 4 ': 84.0, 'Ratin...",2.0,"990 Bay St, Staten Island, NY 10305",40.618362,-74.069453
3,50049689,CHINA RESTAURANT,Brooklyn,11203,7184985108,Chinese,01/25/2022,Violations were cited in the following area(s).,Hot food item not held at or above 140º F.,7.0,...,40.650345,-73.930220,https://www.google.com/maps/place/China+Restau...,4.2,615.0,"{'Rating 5 ': 346.0, 'Rating 4 ': 128.0, 'Rati...",1.0,"937 Utica Ave, Brooklyn, NY 11203",40.650278,-73.930000
4,41382688,GUANTANAMERA,Manhattan,10019,2122625354,Latin American,03/17/2022,Violations were cited in the following area(s).,Mechanical or natural ventilation system not p...,13.0,...,40.765728,-73.983603,https://www.google.com/maps/place/Guantanamera...,4.4,2690.0,"{'Rating 5 ': 1770.0, 'Rating 4 ': 579.0, 'Rat...",2.0,"939 8th Ave, New York, NY 10019",40.765890,-73.983821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
652,50129470,YUMMY,Brooklyn,11226,7183081458,Chinese,10/03/2023,Violations were cited in the following area(s).,Anti-siphonage or back-flow prevention device ...,27.0,...,40.641166,-73.956282,https://www.google.com/maps/place/Yummy/data=!...,3.9,120.0,"{'Rating 5 ': 59.0, 'Rating 4 ': 32.0, 'Rating...",NaN,"1195 Flatbush Ave, Brooklyn, NY 11226",40.641040,-73.955895
653,50008317,EL PATRON RESTAURANT & LOUNGE,Staten Island,10304,3478617065,Mexican,08/28/2023,Violations were cited in the following area(s).,Single service article not provided. Single se...,18.0,...,40.629256,-74.076606,https://www.google.com/maps/place/El+Patron+Re...,3.6,684.0,"{'Rating 5 ': 301.0, 'Rating 4 ': 130.0, 'Rati...",1.0,"520 Bay St, Staten Island, NY 10304",40.629150,-74.076720
654,40381551,CLARK'S RESTAURANT,Brooklyn,11201,7188555484,American,03/27/2023,Violations were cited in the following area(s).,Non-food contact surface or equipment made of ...,12.0,...,40.697511,-73.993260,https://www.google.com/maps/place/Clark%27s+Re...,4.4,1397.0,"{'Rating 5 ': 931.0, 'Rating 4 ': 284.0, 'Rati...",2.0,"80 Clark St, Brooklyn, NY 11201",40.697436,-73.993244
655,50111171,TULCINGO RESTAURANT,Brooklyn,11220,9722510104,Mexican,08/26/2024,Violations were cited in the following area(s).,Non-food contact surface or equipment made of ...,4.0,...,40.642140,-74.013412,https://www.google.com/maps/place/Tulcingo+Res...,3.7,479.0,"{'Rating 5 ': 221.0, 'Rating 4 ': 100.0, 'Rati...",2.0,"5520 5th Ave, Brooklyn, NY 11220",40.642025,-74.013796
656,50105428,JOY INDIAN RESTAURANT,Brooklyn,11217,7188082423,Indian,11/08/2024,Violations were cited in the following area(s).,Live roaches in facility's food or non-food area.,11.0,...,40.678890,-73.973685,https://www.google.com/maps/place/Joy+Indian+R...,4.3,265.0,"{'Rating 5 ': 169.0, 'Rating 4 ': 57.0, 'Ratin...",2.0,"301 Flatbush Ave, Brooklyn, NY 11217",40.678861,-73.973365